[package]
name = "rustdis"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version="1.39.3",features=["full"]}
bytes = {version="1.7.1"}
clap = { version = "4.5.16", features = ["derive"] }
